FROM node:latest

WORKDIR /api-cep
# WORKDIR: nome do espaço de trabalho dentro do container

#COPY: copia tudo que tem na pasta atual do projeto
# para dentro do container com o nome definido no WORKDIR acima
COPY . .

# RUN: O que será rodado no terminal do container,
# nesse caso é pra instalar as dependências do projeto
RUN rm -rf node_modules 
# apaga a pasta node_modules pra instalar tudo no npm install
RUN npm install

CMD ["node", "index.js"]
#roda o arquivo index.js do projeto igual quando rodamos no terminal local 

EXPOSE 3000
#porta que o container vai rodar, ent nesse caso porta: 3000