FROM node:latest

WORKDIR /api-cep
# WORKDIR: nome do espaço de trabalho dentro do container

#COPY: copia tudo que tem na pasta atual do projeto
# para dentro do container com o nome definido no WORKDIR acima
COPY . .

# RUN: O que será rodado no terminal do container,
# nesse caso é pra instalar as dependências do projeto
RUN rm -rf node_modules 
# apaga a pasta node_modules pra instalar tudo no npm install
RUN npm install

# Troque de: CMD ["nodemon", "index.js"]
# Para:

CMD ["npm", "run", "dev"] 
#chamando nodemon que esta no package.json no terminal do docker para rodar e a qualquer alteração já ser atualizado.

EXPOSE 3000
#porta que o container vai rodar, ent nesse caso porta: 3000